In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Crops.csv to Crops.csv


In [ ]:
import numpy as np
import pandas as pd
from time import time

import os
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

data = pd.read_csv("Crops.csv")

data.head()

States  Rainfall  ...  Season                           Crop
0  Andhra Pradesh    110.75  ...  Kharif      Paddy IGKVR-2 (IET 19795)
1  Andhra Pradesh    110.75  ...  Kharif      Paddy IGKVR-2 (IET 19795)
2  Andhra Pradesh    110.75  ...  Kharif  Paddy CR Dhan 501 (IET 19189)
3  Andhra Pradesh    110.75  ...  Kharif  Paddy CR Dhan 501 (IET 19189)
4  Andhra Pradesh    110.75  ...    Rabi    Wheat VL Gehun 907 (VL 907)

[5 rows x 7 columns]

In [ ]:
crop_pred = data['Crop']
crop_input = data.drop('Crop', axis =1)
crop_pred.head()

0        Paddy IGKVR-2 (IET 19795)
1        Paddy IGKVR-2 (IET 19795)
2    Paddy CR Dhan 501 (IET 19189)
3    Paddy CR Dhan 501 (IET 19189)
4      Wheat VL Gehun 907 (VL 907)
Name: Crop, dtype: object

In [ ]:
crop_input.head()

States  Rainfall  Ground Water  Temperature Soil type  Season
0  Andhra Pradesh    110.75          9.74         31.5  Alluvial  Kharif
1  Andhra Pradesh    110.75          9.74         31.5    Clayey  Kharif
2  Andhra Pradesh    110.75          9.74         33.0  Alluvial  Kharif
3  Andhra Pradesh    110.75          9.74         33.0    Clayey  Kharif
4  Andhra Pradesh    110.75          9.74         20.5    Clayey    Rabi

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
numerical = ['Rainfall', 'Ground Water', 'Temperature']
crop_transform = pd.DataFrame(data =crop_input)


In [ ]:
crop_transformed = crop_transform.drop('States', axis=1)
features_final = pd.get_dummies(crop_transformed)
crop_transformed.head()

Rainfall  Ground Water  Temperature Soil type  Season
0    110.75          9.74         31.5  Alluvial  Kharif
1    110.75          9.74         31.5    Clayey  Kharif
2    110.75          9.74         33.0  Alluvial  Kharif
3    110.75          9.74         33.0    Clayey  Kharif
4    110.75          9.74         20.5    Clayey    Rabi

In [ ]:
features_final.head()

Rainfall  Ground Water  Temperature  ...  Season_Kharif  Season_Rabi  Season_Zaid
0    110.75          9.74         31.5  ...              1            0            0
1    110.75          9.74         31.5  ...              1            0            0
2    110.75          9.74         33.0  ...              1            0            0
3    110.75          9.74         33.0  ...              1            0            0
4    110.75          9.74         20.5  ...              0            1            0

[5 rows x 13 columns]

In [ ]:
factor = pd.factorize(data['Crop'])
data.Crop = factor[0]
definitions = factor[1]
print(data.Crop.head())
print(definitions)

0    0
1    0
2    1
3    1
4    2
Name: Crop, dtype: int64
Index(['Paddy IGKVR-2 (IET 19795)', 'Paddy CR Dhan 501 (IET 19189)',
       'Wheat VL Gehun 907 (VL 907)', 'Wheat WHD 943',
       'Millet Nandi-65 (MH-1549)', 'Lentil Pant Lentil-8(Pant L-063)',
       'Bajra', 'Cardamom', 'Urad', 'Jowar', 'Paddy CR Dhan 401 (REETA)',
       'Millet MH 1540 (86M64) (Hybrid)', 'Sugarcane Karan 5 (Co 0124)',
       'Clove', 'Banana', 'Moong', 'Arhar', 'Oilseed', 'Tea', 'Coffee',
       'Turmeric', 'Cashewnut', 'Ragi', 'Soyabean', 'Black Gram', 'Khesari',
       'Wheat MACS 6222', 'Black Pepper', 'Chillies', 'Garlic',
       'Wheat MPO(JW) 1215 (MPO 1215)', 'Maize PMH 5 (JH 3110)',
       'Groundnut Kadiri Harithandhra (K 1319)', 'Groundnut GPBD 5',
       'Lentil Pant Lentil-7(Pant L-024)', 'Tobacco', 'Tomato', 'Cocoa',
       'Rubber', 'Masoor', 'Sunhemp', 'Varagu',
       'Paddy CR Dhan 601 (IET 18558)', 'Wheat Netravati (NIAW 1415)',
       'Maize HSC1', 'Millet Nandi-61 (MH-1548)',
       '

In [ ]:
X =features_final.iloc[:].values
y = data.iloc[:,6].values
print('The independent features set: ')
print(X[:5,:])
print('The dependent variable: ')
print(y[:5])

The independent features set: 
[[110.75   9.74  31.5    1.     0.     0.     0.     0.     0.     0.
    1.     0.     0.  ]
 [110.75   9.74  31.5    0.     0.     1.     0.     0.     0.     0.
    1.     0.     0.  ]
 [110.75   9.74  33.     1.     0.     0.     0.     0.     0.     0.
    1.     0.     0.  ]
 [110.75   9.74  33.     0.     0.     1.     0.     0.     0.     0.
    1.     0.     0.  ]
 [110.75   9.74  20.5    0.     0.     1.     0.     0.     0.     0.
    0.     1.     0.  ]]
The dependent variable: 
[0 0 1 1 2]


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state= 21 )


print("Training set has {} samples.".format(X_train.shape[0]))

print("Testing set has {} samples.".format(X_test.shape[0]))


Training set has 697 samples.
Testing set has 124 samples.


In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(max_depth =35, max_features =10 , random_state = 42 , ccp_alpha = 0.0022 , criterion="gini" )
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0022, class_weight=None, criterion='gini',
                       max_depth=35, max_features=10, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=42, splitter='best')

In [ ]:
y_pred = classifier.predict(X_test)
reversefactor = dict(zip(range(77),definitions))
y_test = np.vectorize(reversefactor.get)(y_test)
y_pred = np.vectorize(reversefactor.get)(y_pred)
# Making the Confusion Matrix
print(pd.crosstab(y_test, y_pred, rownames=['Actual Crop'], colnames=['Predicted Crop']))

Predicted Crop                    Banana  ...  Wheat VL Gehun 907 (VL 907)
Actual Crop                               ...                             
Bajra                                  0  ...                            0
Banana                                 6  ...                            0
Black Gram                             0  ...                            0
Black Pepper                           0  ...                            0
Cardamom                               0  ...                            0
Cashewnut                              0  ...                            0
Clove                                  0  ...                            0
Cocoa                                  0  ...                            0
Coffee                                 0  ...                            0
Cotton CNH012                          0  ...                            0
Cowpea                                 0  ...                            0
Dry Ginger               

In [ ]:
from sklearn.metrics import fbeta_score, accuracy_score, precision_score, recall_score

print("Accuracy on testing data: {:.4f}".format(accuracy_score(y_test, y_pred)))
print("F-score on testing data: {:.4f}".format(fbeta_score(y_test, y_pred, average='weighted', beta = 0.5)))
print("Precision on testing data: {:.4f}".format(precision_score(y_test, y_pred,average='weighted')))
print("Recall on testing data: {:.4f}".format(recall_score(y_test, y_pred,average='weighted')))


Accuracy on testing data: 0.8065
F-score on testing data: 0.7715
Precision on testing data: 0.7716
Recall on testing data: 0.8065


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
X_test

array([[125.6 ,   7.5 ,  30.  , ...,   0.  ,   0.  ,   1.  ],
       [250.  ,   9.  ,  22.5 , ...,   0.  ,   0.  ,   0.  ],
       [ 30.  ,   3.8 ,  28.5 , ...,   0.  ,   1.  ,   0.  ],
       ...,
       [110.75,   9.74,  20.5 , ...,   0.  ,   1.  ,   0.  ],
       [ 87.5 ,   8.  ,  25.  , ...,   1.  ,   0.  ,   0.  ],
       [137.5 ,  12.3 ,  27.5 , ...,   0.  ,   1.  ,   0.  ]])

In [ ]:
''' Prediction Function '''

def prediction(arr) :

  a=classifier.predict(arr)
  a = np.vectorize(reversefactor.get)(a)
  return a


In [ ]:
location = 'Assam'
temperature = '25'
soil_type= 'Alluvial'
season = 'Kharif'

In [ ]:
crop_dict_one = {'Andhra Pradesh': np.array([[110.75, 9.74]]), 'Assam' : np.array([[156.2, 1.62]]), 'Bihar': np.array([[125.6,7.5]]), 'Chhattisgarh' : np.array([[130.4, 5]]) , 'Goa' : np.array([[295, 13]]), 'Gujrat': np.array([[115.7,35]]), 'Haryana' : np.array([[47.5, 15]]), 'Himachal Pradesh' :np.array([[127.5, 22]]), 'Jharkhand': np.array([[121.4,12]]), 'Karnataka' : np.array([[121.4, 22]]), 'Kerala' : np.array([[315.7, 20]]), 'Madhya Pradesh': np.array([[235.5,22]]), 'Maharashtra' : np.array([[246, 3.2]]), 'Manipur' : np.array([[148.8, 4]]),'Meghalaya': np.array([[117.5,4]]), 'Mizoram' : np.array([[257, 8]]), 'Nagaland' : np.array([[215, 18.1]]), 
             'Odisha': np.array([[215,5]]),'Punjab' : np.array([[60, 8.9]]), 'Rajasthan' : np.array([[48.8, 32]]), 'Sikkim': np.array([[299.5,50]]),
             'Tamil Nadu' : np.array([[145, 16.67]]),'Telangana' :np.array([[87.5, 8]]), 'Tripura': np.array([[238.5,6.7]]), 'Uttar Pradesh' : np.array([[134.65, 6]]), 'Uttarakhand' : np.array([[164.5, 7.5]]), 
             'West Bengal': np.array([[250,9]]), 'Andaman and Nicobar Islands' : np.array([[277, 3.5]]), 'Dadra & Nagar Haveli and Daman & Diu' : np.array([[89, 2]]),
             'Chandigarh': np.array([[105.5,28]]), 'Jammu and Kashmir': np.array([[111.5,17]]), 'Delhi' : np.array([[90,6.7]]),
             'Lakshdweep' : np.array([[30, 3.8]]), 'Puducherry': np.array([[137.5,12.3]]), 'Ladakh' : np.array([[15,22.3]])  }

for i,j in crop_dict_one.items() :
  if i==location :
    loc = j    

In [ ]:
temp = np.array([[float(temperature)]])

In [ ]:
crop_dict_two = {'Alluvial': np.array([[1,0,0,0,0,0]]), 'Black':np.array([[0,1,0,0,0,0]]), 'Clayey': np.array([[0,0,1,0,0,0]]), 'Latterite': np.array([[0,0,0,1,0,0]]),  
                 'Red': np.array([[0,0,0,0,1,0]]), 'Sandy':np.array([[0,0,0,0,0,1]]) }

for a,b in crop_dict_two.items() :
  if a==soil_type :
    soil = b                  

In [ ]:
crop_dict_three = { 'All Season': np.array([[1,0,0,0]]), 'Kharif': np.array([[0,1,0,0]]), 'Rabi': np.array([[0,0,1,0]]), 'Zaid': np.array([[0,0,0,1]]) }

for c,d in crop_dict_three.items() :
  if c==season :
    season_ = d 

In [ ]:
final_arr = np.hstack((loc, temp, soil, season_))

final_arr

array([[156.2 ,   1.62,  25.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,
          0.  ,   0.  ,   1.  ,   0.  ,   0.  ]])

In [ ]:
predicted_crop = prediction(final_arr)
print("The predicted Crop is :", predicted_crop )


The predicted Crop is : ['Tea']


In [ ]:
uploaded_2 = files.upload()

Saving Prediction.csv to Prediction.csv


In [ ]:
additional_info = pd.read_csv('Prediction.csv')

In [ ]:
additional_info.head()

Crops  ...            Crops for mixed cropping
0      Paddy IGKVR-2 (IET 19795)  ...                     Gram, Groundnut
1  Paddy CR Dhan 501 (IET 19189)  ...                     Gram, Groundnut
2    Wheat VL Gehun 907 (VL 907)  ...     Horse Gram, Black Gram, Mustard
3                  Wheat WHD 943  ...     Horse Gram, Black Gram, Mustard
4      Millet Nandi-65 (MH-1549)  ...  Black gram, Moong, Cowpea, Sorghum

[5 rows x 8 columns]

In [ ]:
crop_string = predicted_crop[0]

final_df = additional_info[additional_info['Crops'].str.contains(crop_string)]

fertilisers =final_df['Fertilisers required'].values[0]
cost_of_cultivation = final_df['Cost of cultivation'].values[0]
expected_revenues = final_df['Expected revenues'].values[0]
seeds_required = final_df['Quantity of seeds per hectare'].values[0]
duration_cultivation = final_df['Duration of cultivation'].values[0]
mixed_cropping = final_df['Crops for mixed cropping'].values[0]

final_df

Crops Fertilisers required  ... Demand of crop Crops for mixed cropping
18   Tea      UT 752,Dolomite  ...           High    Cocoa, Coffee, Rubber

[1 rows x 8 columns]

In [ ]:
print("Most Suitable Crop to Grow is :", crop_string)
print("The Fertilisers that are required is/are :", fertilisers)
print("Cost of Cultivation will be : Rs.", cost_of_cultivation)
print("Expected Revenues : Rs.", expected_revenues )
print("Quantity of Seeds Required per Hectare : ", seeds_required)
print("Expected Duration of Cultivation :", duration_cultivation, " Days")
print("Optional Crop(s) for Mixed Cropping is/are :", mixed_cropping)

Most Suitable Crop to Grow is : Tea
The Fertilisers that are required is/are : UT 752,Dolomite
Cost of Cultivation will be : Rs. 5,023
Expected Revenues : Rs. 353763
Quantity of Seeds Required per Hectare :  1650kg
Expected Duration of Cultivation : 60-65  Days
Optional Crop(s) for Mixed Cropping is/are : Cocoa, Coffee, Rubber
